### ISSUE TITLE
Utilise zoom verification token

### ISSUE THREAD

**Issue by Viv-Rajkumar** [natterstefan/zoom-slack-status-updater#4]
## Feature Request

As the title suggested, Zoom provides an authorisation/verification token which can be checked to ensure the now.sh url is not updating slack status for un-auth requests.

### Motivation

To address the "Tip" limitation documented in the README.

I was locally able to do the same by adding a new `now secret` for a ZOOM_TOKEN and checking if its available && matches the incoming Auth header to have the same supported. I can submit a PR for the same if its beneficial, should this also be a config option from src/config.js that a user can set inline similar to slack_token if not wanting to use `now secret` ?

PS: cheers for publishing this utility. Been very helpful managing Zoom statuses for slack.

**Comment by natterstefan** [comment]
Hi @Viv-Rajkumar,

thanks for making me aware of the verification token ([source](https://marketplace.zoom.us/docs/guides/build/webhook-only-app#features-2)):

> A verification token will be generated in the Feature page after you enable and save the event subscription. This token can be used to validate the POST requests that are sent by Zoom to your event notification endpoint URL.

It would be really helpful to me and others when you create a PR for this missing feature. I'd make sure it works similar to `process.env.SLACK_TOKEN_n`. So yes, both in the [config](https://github.com/natterstefan/zoom-slack-status-updater/blob/master/slack-status-config-example.js#L16-L19) and as a [`now secret`](https://github.com/natterstefan/zoom-slack-status-updater/blob/master/now-example.json#L4), please.

Thank you very much and you're welcome :)

**Comment by natterstefan** [comment]
Hi @Viv-Rajkumar,

I resolved this feature request yesterday (see [CHANGELOG](https://github.com/natterstefan/zoom-slack-status-updater/blob/master/CHANGELOG.md#features)).

Simply add the `zoomVerificationToken` to the workspace config and you are good to go.

```diff
module.exports = [
  {
    name: 'Slack Workspace 1',
    email: 'your-address@mail.com',
    token: 'xoxp-xxx-xxx',
+    zoomVerificationToken: 'Vivamusultricies',
    meetingStatus: {
      text: "I'm in a meeting",
      emoji: ':warning:', // emoji code
    },
    noMeetingStatus: {
      text: '',
      emoji: '',
    },
  },
]

Enjoy your day.

**Comment by Viv-Rajkumar** [comment]
Sorry I missed your previous message in the thread but looks like you've sorted it yourself :)
